### ISSUE TITLE
AttributeError: module 'netbox_proxbox.proxbox_api' has no attribute 'update

### ISSUE THREAD

**Issue by CodeBleu** [netdevopsbr/netbox-proxbox#132]
Trying new multi-cluster feature and am getting the following:

https://github.com/orgs/netdevopsbr/discussions/131

![image](https://github.com/netdevopsbr/netbox-proxbox/assets/400979/59efb5d5-5fa8-40ba-accb-553c46a1ccc9)

│ Internal Server Error: /plugins/proxbox/single_update/ │
│ Traceback (most recent call last): │
│ File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner │
│ response = get_response(request) │
│ File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response │
│ response = wrapped_callback(request, *callback_args, **callback_kwargs) │
│ File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view ││ return self.dispatch(request, *args, **kwargs) ││ File "/opt/netbox/venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch ││ return super().dispatch(request, *args, **kwargs) ││ File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatch ││ return handler(request, *args, **kwargs) ││ File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_proxbox/views.py", line 150, in post ││ json_result = proxbox_api.update.single(remove_unused = True, proxmox_domain = proxmox_domain) ││ AttributeError: module 'netbox_proxbox.proxbox_api' has no attribute 'update' ││ x.x.x.x- - [24/Jul/2023:13:14:08 +0000] "POST /plugins/proxbox/single_update/ HTTP/1.1" 500 1631 "http://testbox:8000/plugins/proxbox/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36" ││ 127.0.0.1 - - [24/Jul/2023:13:14:11 +0000] "GET /api/ HTTP/1.1" 200 510 "-" "curl/7.81.0" ││ Internal Server Error: /plugins/proxbox/full_update/ ││ Traceback (most recent call last): ││ File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner ││ response = get_response(request) ││ File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response ││ response = wrapped_callback(request, *callback_args, **callback_kwargs) ││ File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view ││ return self.dispatch(request, *args, **kwargs) ││ File "/opt/netbox/venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch ││ return super().dispatch(request, *args, **kwargs) ││ File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatch ││ return handler(request, *args, **kwargs) ││ File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_proxbox/views.py", line 173, in get ││ json_result = proxbox_api.update.all(remove_unused = True) ││ AttributeError: module 'netbox_proxbox.proxbox_api' has no attribute 'update' │

**Comment by CodeBleu** [comment]
Issue resolved with #135
