### ISSUE TITLE
im getting this error whentrying to run the migrate command part of install

### ISSUE THREAD

**Issue by pzhitnikov** [netdevopsbr/netbox-proxbox#138]
(venv) root@netbox:/opt/netbox/netbox# python3 manage.py collectstatic --no-input
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 386, in execute
    settings.INSTALLED_APPS
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/settings.py", line 687, in <module>
    plugin = importlib.import_module(plugin_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_proxbox/__init__.py", line 40, in <module>
    from . import proxbox_api
  File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_proxbox/proxbox_api/__init__.py", line 1, in <module>
    from . import (
  File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_proxbox/proxbox_api/update.py", line 2, in <module>
    from .plugins_config import (
  File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_proxbox/proxbox_api/plugins_config.py", line 73, in <module>
    PROXMOX = PROXMOX_SETTING.get("domain", DEFAULT_PROXMOX)
AttributeError: 'list' object has no attribute 'get'

**Comment by lug-gh** [comment]
For me the same, but already one step before yours.
`(venv) root@netbox:/opt/netbox/netbox# python3 manage.py migrate`

**Comment by lug-gh** [comment]
It seems like the plugins_config.py is not working with multi-cluster.
In like 73 you can see it want's to load a value rom a list, but it's not defined which object in the list.

So if you don't use multi-cluster you can remove the brackets `[ ]` from `/opt/netbox/netbox/netbox/configuration.py` in the PLUGINS_CONFIG section, or the script has to be fixed to be able to read a multi-cluster.

Multi-cluster does not mean multiple servers in a cluster, but actually multiple proxmox clusters that you want to have in netbox.
So if you have only one cluster of x servers, you can safely remove the square brackets for now.

**Comment by pzhitnikov** [comment]
If I have 1 host instead of a cluster, then the integration in this way does not make sense?
Yes you are right. Removing `[]` solves the problem in `python3 manage.py migrate`

**Comment by lug-gh** [comment]
> If I have 1 host instead of a cluster, then the integration in this way does not make sense?`

Right, it's just wrong or insufficient documentation if you can't read and debug source code. But that's how it is with open-source, the code is free, but you have no claims to be taught by the maintainer. The knowledge transfer happens in the community.

**Comment by pzhitnikov** [comment]
Thank you

**Comment by lug-gh** [comment]
Can you reopen the issue? It's not solved, you just did a workaround, but the root cause is still there :)
