### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by messyjoes** [netdevopsbr/netbox-proxbox#146]
Hello,
I install and configure the plugin according to the instructions.
netbox-proxbox installed via pip.
Using: Debian 12, Python 3.11, Netbox v3.6.0, netbox-proxbox 0.0.5
However, after executing `python3 manage.py migrate` I get an error:
```
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/settings.py", line 728, in <module>
    plugin = importlib.import_module(plugin_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_proxbox/__init__.py", line 40, in <module>
    from . import proxbox_api
  File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_proxbox/proxbox_api/__init__.py", line 1, in <module>
    from . import (
  File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_proxbox/proxbox_api/update.py", line 2, in <module>
    from .plugins_config import (
  File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_proxbox/proxbox_api/plugins_config.py", line 73, in <module>
    PROXMOX = PROXMOX_SETTING.get("domain", DEFAULT_PROXMOX)
              ^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
```
configuration.py:
```
# Enable installed plugins. Add the name of each plugin to the list.
PLUGINS = ['netbox_proxbox']

# Plugins configuration settings. These settings are used by various plugins that the user may have installed.
# Each key in the dictionary is the name of an installed plugin and its value is a dictionary of settings.
PLUGINS_CONFIG = {
    'netbox_proxbox': {
        'proxmox': [
            {
                'domain': '192.168.111.10',    # May also be IP address
                'http_port': 8006,
                'user': 'root@pam',   # always required
                #'password': 'Strong@P4ssword', # only required, if you don't want to use token based authentication
                'token': {
                    'name': 'netbox',   # Only type the token name and not the 'user@pam:tokenID' format
                    'value': '***'  # I use token
                },
                'ssl': False
            }
        ],
        'netbox': {
            'domain': 'localhost',     # Ensure localhost is added to ALLOWED_HOSTS
            'http_port': 8001,     # Gunicorn port.
            'token': '***',
            'ssl': False,       # There is no support to SSL on Netbox yet, so let it always False.
            'settings': {
                'virtualmachine_role_id' : 0,
                'node_role_id' : 0,
                'site_id': 0
            }
        }
    }
}
```

**Comment by jmbwell** [comment]
I’m seeing this today with fresh installations of netbox and the plug-in. I’ve tried with these configuration variables in extra.py also, with the same results.

**Comment by bilbolodz** [comment]
I've got the same error

**Comment by chodorenko** [comment]
You configure Proxbox whitch config to Multicluster configuration 0.6.0,  please use [old format](https://github.com/netdevopsbr/netbox-proxbox/blob/b850c234485fce4414baf4d0affaf09bfa6524a7/README.md)

**Comment by bilbolodz** [comment]
But how to specify more than one proxmox cluster using "old format"?

**Comment by chodorenko** [comment]
Multicluster addided in developer tree and complete in 0.6.0 release. Now multicluster is not stable,  you can view its in Issues. Version 0.5.0 not support multicluster and use old config format.
Answer on you question -> You can  not use multicluster on 0.5.0 an old format config

**Comment by bilbolodz** [comment]
So "multicluster is NOT ready" yet and don't use it, right?

**Comment by messyjoes** [comment]
> You configure Proxbox whitch config to Multicluster configuration 0.6.0, please use [old format](https://github.com/netdevopsbr/netbox-proxbox/blob/b850c234485fce4414baf4d0affaf09bfa6524a7/README.md)

Yep, it works! Thanks.

Current configuration.py:
```
PLUGINS_CONFIG = {
    'netbox_proxbox': {
        'proxmox': {
            'domain': '192.168.111.10',    # May also be IP address
            'http_port': 8006,
            'user': 'root@pam',   # always required
            'password': '', # only required, if you don't want to use token based authentication
            'token': {
                'name': 'netbox',       # Only type the token name and not the 'user@pam:tokenID' format
                'value': '***'
            },
            'ssl': False
        },
        'netbox': {
            'domain': 'localhost',     # Ensure localhost is added to ALLOWED_HOSTS
            'http_port': 8001,     # Gunicorn port.
            'token': '***',
            'ssl': False,       # There is no support to SSL on Netbox yet, so let it always False.
            'settings': {
                'virtualmachine_role_id' : 0,
                'node_role_id' : 0,
                'site_id': 0
            }
        }
    }
}
```
