### ISSUE TITLE
CLOSED

### ISSUE THREAD

**Issue by SurFicE** [netdevopsbr/netbox-proxbox#160]
Good day
When I try to run the command "python3 manage.py migrate", I get an error:
`**(venv) root@netbox:/opt/netbox/netbox# python3 manage.py migrate**
Traceback (most recent call last):
  File "/opt/netbox-3.6.5/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox-3.6.5/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox-3.6.5/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/opt/netbox-3.6.5/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/opt/netbox-3.6.5/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/netbox-3.6.5/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/netbox-3.6.5/netbox/netbox/settings.py", line 737, in <module>
    plugin = importlib.import_module(plugin_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/netbox-3.6.5/venv/lib/python3.9/site-packages/netbox_proxbox/__init__.py", line 40, in <module>
    from . import proxbox_api
  File "/opt/netbox-3.6.5/venv/lib/python3.9/site-packages/netbox_proxbox/proxbox_api/__init__.py", line 1, in <module>
    from . import (
  File "/opt/netbox-3.6.5/venv/lib/python3.9/site-packages/netbox_proxbox/proxbox_api/update.py", line 2, in <module>
    from .plugins_config import (
  File "/opt/netbox-3.6.5/venv/lib/python3.9/site-packages/netbox_proxbox/proxbox_api/plugins_config.py", line 73, in <module>
    PROXMOX = PROXMOX_SETTING.get("domain", DEFAULT_PROXMOX)
AttributeError: 'list' object has no attribute 'get'`
OS version Debian 11

I would be extremely grateful for your help

**Comment by ghost** [comment]
Running into the same issue, did you find a solution?

**Comment by k3snoob** [comment]
> Running into the same issue, did you find a solution?

See issue #146, you need to remove the square brackets that surround the multi-cluster config so that it's no longer looking for a list.

**Comment by emersonfelipesp** [comment]
This issue does not happen anymore, as PLUGIN configuration was moved from NetBox configuration.py file directly to NetBox GUI or REST API.
