### ISSUE TITLE
Support version 3.7.1

### ISSUE THREAD

**Issue by DrKeks1993** [netdevopsbr/netbox-proxbox#165]
Is netbox version 3.7.1 supported? I can't run `python 3 manage.py migrate`

```
 Traceback (most recent call last):
   File "/opt/netbox-3.7.1/netbox/manage.py", line 10, in <module>
     execute_from_command_line(sys.argv)
   File "/opt/netbox-3.7.1/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
     utility.execute()
   File "/opt/netbox-3.7.1/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 382, in execute
     settings.INSTALLED_APPS
   File "/opt/netbox-3.7.1/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
     self._setup(name)
   File "/opt/netbox-3.7.1/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in _setup
     self._wrapped = Settings(settings_module)
   File "/opt/netbox-3.7.1/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 217, in __init__
     mod = importlib.import_module(self.SETTINGS_MODULE)
   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
   File "/opt/netbox-3.7.1/netbox/netbox/settings.py", line 748, in <module>
     plugin = importlib.import_module(plugin_name)
   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
   File "/opt/netbox-3.7.1/venv/lib/python3.10/site-packages/netbox_proxbox/__init__.py", line 40, in <module>
     from . import proxbox_api
   File "/opt/netbox-3.7.1/venv/lib/python3.10/site-packages/netbox_proxbox/proxbox_api/__init__.py", line 1, in <module>
     from . import (
   File "/opt/netbox-3.7.1/venv/lib/python3.10/site-packages/netbox_proxbox/proxbox_api/update.py", line 2, in <module>
     from .plugins_config import (
   File "/opt/netbox-3.7.1/venv/lib/python3.10/site-packages/netbox_proxbox/proxbox_api/plugins_config.py", line 66, in <module>
     PROXMOX_SETTING = USER_PLUGINS_CONFIG.get("proxmox", DEFAULT_PROXMOX_SETTING)
 AttributeError: 'NoneType' object has no attribute 'get'
```

My configuration.py :

```
 {
     'netbox_proxbox': {
         'proxmox': {
             'domain': 'my_ip',    # May also be IP address
             'http_port': 8006,
             'user': 'root@pam',   # always required
             'password': 'my_pass', # only required, if you don't want to use token based authentication
             'token': {
                 'name': 'netbox',  # Only type the token name and not the 'user@pam:tokenID' format
                 'value': 'token'
             },
             'ssl': False
         },
         'netbox': {
             'domain': 'localhost',     # Ensure localhost is added to ALLOWED_HOSTS
             'http_port': 8001,     # Gunicorn port.
             'token': 'noken',
             'ssl': False,   # There is no support to SSL on Netbox yet, so let it always False.
             'settings': {
                 'virtualmachine_role_id' : 0,
                 'node_role_id' : 0,
                 'site_id': 0
             }
         }
     }
 }
```

**Comment by itrf98** [comment]
this should solve your issue:

https://github.com/netdevopsbr/netbox-proxbox/issues/146

**Comment by DrKeks1993** [comment]
> this should solve your issue:
> 
> #146

I've read this thread, but I don't understand what I'm doing wrong. I don't use a multicluster.

**Comment by emersonfelipesp** [comment]
#176
