### ISSUE TITLE
object has no attribute "slug"

### ISSUE THREAD

**Issue by gfvh** [netdevopsbr/netbox-proxbox#173]
Performing proxmox full update happens this:

<class 'AttributeError'>

object has no attribute "slug"

Python version: 3.11.2
NetBox version: 3.7.1
Plugins: 
  netbox_attachments: 4.0.2
  netbox_ipcalculator: 1.1
  netbox_proxbox: 0.0.5
  netbox_qrcode: 0.0.11
  netbox_topology_views: 3.9.0
  
  here is cat from log of exact moment

log file: 

[netbox_proxmox.log](https://github.com/netdevopsbr/netbox-proxbox/files/15202018/netbox_proxmox.log)
  
cat /var/log/netbox.log
  

> 

Internal Server Error: /plugins/proxbox/full_update/
Traceback (most recent call last):
  File "/opt/netbox-3.7.1/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-3.7.1/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-3.7.1/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-3.7.1/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-3.7.1/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-3.7.1/venv/lib/python3.11/site-packages/netbox_proxbox/views.py", line 93, in get
    "virtualmachines_table": VMUpdateResult(proxbox_api.update.all(remove_unused = True)["virtualmachines"]),
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-3.7.1/venv/lib/python3.11/site-packages/netbox_proxbox/proxbox_api/update.py", line 420, in all
    cluster = create.virtualization.cluster()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-3.7.1/venv/lib/python3.11/site-packages/netbox_proxbox/proxbox_api/create/virtualization.py", line 68, in cluster
    type = cluster_type().slug
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox-3.7.1/venv/lib/python3.11/site-packages/pynetbox/core/response.py", line 308, in __getattr__
    raise AttributeError('object has no attribute "{}"'.format(k))
AttributeError: object has no attribute "slug"

**Comment by emersonfelipesp** [comment]
#176
